[kodama]
trees = "trees"
assets = "assets"
base-url = "/"
themes = [
  "themes/moon.html", 
  "themes/default.html",
  "themes/zenwritten.html",
]

[toc]
placement = "right"
sticky = true
mobile-sticky = true
max-width = "max-content"

[text]
edit = "[edit]"
toc = "Table of Contents"
references = "References"
backlinks = "Backlinks"

[build]
typst-root = "trees"
short-slug = true
pretty-urls = true
footer-mode = "link"
inline-css = true
asref = true
output = "./publish"

[serve]
edit = "vscode://file/"
output = "./.cache/publish"
command = ["miniserve", "<output>", "--index", "index.html", "--pretty-urls", "--port", "8080"]
